// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOXtW863XCA9vQb9Me3MsjKj6f4otww_8',
    appId: '1:93012964636:android:123c700a8b1ef42b7936d9',
    messagingSenderId: '93012964636',
    projectId: 'ace-tennis-41dc7',
    storageBucket: 'ace-tennis-41dc7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAio6zoK7pBf831q1WWIEH3eO1TwyJYB7c',
    appId: '1:93012964636:ios:42994091cba8fc357936d9',
    messagingSenderId: '93012964636',
    projectId: 'ace-tennis-41dc7',
    storageBucket: 'ace-tennis-41dc7.firebasestorage.app',
    iosBundleId: 'com.courtconnect.aceApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn_GTvt0JQVZobk8oRYPIhXEkzqijD9Ls',
    appId: '1:93012964636:web:809748437e6f0d327936d9',
    messagingSenderId: '93012964636',
    projectId: 'ace-tennis-41dc7',
    authDomain: 'ace-tennis-41dc7.firebaseapp.com',
    storageBucket: 'ace-tennis-41dc7.firebasestorage.app',
    measurementId: 'G-R1GHXPNWC2',
  );
}
