name: ace_app
description: "CourtConnect - Application de réservation de terrains de tennis"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^14.6.3

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # UI
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  intl: ^0.19.0

  # Firebase
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.12
  # firebase_auth: ^5.0.0
  # firebase_messaging: ^15.0.0

  # Utils
  uuid: ^4.5.1
  equatable: ^2.0.7
  rxdart: ^0.28.0
  url_launcher: ^6.3.2
  share_plus: ^13.3.0
  firebase_auth: ^5.7.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.1
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
