import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/booking_scenario.dart';

class BookingScenarioRepository {
  BookingScenarioRepository({FirebaseFirestore? firestore})
    : _firestore = firestore ?? FirebaseFirestore.instance;

  final FirebaseFirestore _firestore;

  CollectionReference<Map<String, dynamic>> get _collection =>
      _firestore.collection('bookingScenarios');

  Future<List<BookingScenario>> fetchAll() async {
    final snapshot = await _collection.get();
    return snapshot.docs
        .map((doc) => BookingScenario.fromJson({...doc.data(), 'id': doc.id}))
        .toList();
  }

  Stream<List<BookingScenario>> watchAll() {
    return _collection.snapshots().map(
      (snapshot) => snapshot.docs
          .map((doc) => BookingScenario.fromJson({...doc.data(), 'id': doc.id}))
          .toList(),
    );
  }

  /// Admin-only — creates a new scenario at `scenario.id` (pre-generated by
  /// the caller, same convention as `CourtRepository.create`).
  Future<void> create(BookingScenario scenario) {
    return _collection.doc(scenario.id).set(scenario.toJson());
  }

  /// Admin-only — full replace of an existing scenario's document.
  Future<void> update(BookingScenario scenario) {
    return _collection.doc(scenario.id).set(scenario.toJson());
  }

  /// Admin-only — deletes a scenario. Courts referencing it (`scenarioId`)
  /// simply fall back to default booking rules; they aren't touched.
  Future<void> delete(String scenarioId) {
    return _collection.doc(scenarioId).delete();
  }
}
